version: '3.8'
services:
    tourguide:
        image: tourguide
        restart: always
        ports:
            - "8080:8080"
        environment:
            TOURGUIDE_GPSUTIL : gpsutil:8081
            TOURGUIDE_REWARDS : rewards:8082
            TOURGUIDE_TRIPPRICE : trippricer:8083
        depends_on:
            -   gpsutil
            -   rewards
            -   trippricer
        container_name: tourguide

    gpsutil:
        image: gpsutil
        restart: always
        ports:
            - "8081:8081"
        container_name: gpsutil

    rewards:
        image: rewards
        restart: always
        ports:
            -   "8082:8082"
        container_name: rewards

    trippricer:
        image: trippricer
        restart: always
        ports:
            -   "8083:8083"
        container_name: trippricer